import { ChurchInfo, SermonItem, ProgramEventItem, TeamMemberItem } from './types';

export const churchInfo: ChurchInfo = {
  name: "ALL SOUL'S WINNING FOR SAVIOUR GLOBAL MINISTRY",
  shortName: 'ASWS Global Ministry',
  tagline:
    'Come experience the joy of belonging to a faith community that values community, worship, and purpose.',
  motto: 'Leading with faith, wisdom, and a heart for souls',
  address: 'Ayedire area behind royal college Ogbomosho, Oyo state, Nigeria',
  phone: '08035745728',
  email: 'oyegbilejames@gmail.com',
  pastor: "REV'D James Oyegbile",
  logoUrl: '/image/ALL_SOULS_WINNING_FOR_SAVIOUR_GLOBAL_MINISTRY-removebg-preview.png',
  copyrightYear: 2025,
  serviceTimes: {
    sundayService: 'Sunday Service: 9:30 AM - 12:00 PM',
    sundaySchool: 'Sunday School: 8:00 AM - 9:30 AM',
    workersPrayer: 'Workers Prayer: 7:00 AM - 8:00 AM',
    midweekPrayer: 'Wednesday Prayer: 9:00 AM - 12:00 PM',
    bibleStudy: 'Tuesday Bible Study: 5:00 PM - 6:30 PM',
  },
  socialLinks: {
    facebook: '#',
    youtube: '#',
    instagram: '#',
  },
  bankDetails: {
    bankName: 'GT BANK',
    accountName: 'Oyegbile James akinloye',
    accountNumber: '0049625425',
  },
};

export const initialSermons: SermonItem[] = [
  {
    id: 'sermon-1',
    title: 'The Power of Forgiveness',
    speaker: "REV'D James Oyegbile",
    date: '2024-10-27',
    description:
      'Discover the freedom that comes from forgiving others as Christ has forgiven us.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-2',
    title: 'Living a Life of Purpose',
    speaker: 'Pastor Adetunji Adeyanju',
    date: '2024-10-20',
    description: "Learn how to find and follow God's unique purpose for your life.",
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-3',
    title: 'Faith in Times of Trial',
    speaker: "REV'D James Oyegbile",
    date: '2024-10-13',
    description: 'A message of hope and perseverance through faith.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-4',
    title: 'The Joy of Giving',
    speaker: 'Pastor Tunde Adegboyega',
    date: '2024-10-06',
    description: 'Understanding the blessings that come with a generous heart.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-5',
    title: 'Walking in the Spirit',
    speaker: "REV'D James Oyegbile",
    date: '2024-09-29',
    description: 'How to live a life led by the Holy Spirit every day.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-6',
    title: 'Love Your Neighbor',
    speaker: 'Pastor Adetunji Adeyanju',
    date: '2024-09-22',
    description: "Practical ways to show Christ's love to those around you.",
    videoUrl: '#',
    audioUrl: '#',
  },
];

export const initialEvents: ProgramEventItem[] = [
  {
    id: 'prog-1',
    title: 'Sunday Services',
    dayOrFrequency: 'SUNDAY',
    time: 'Workers Prayer (7:00am-8:00am) | Sunday School (8:00am-9:30am) | Sunday Service (9:30am-12:00pm)',
    description: 'Our main worship service, Sunday school, and workers preparation prayer.',
    category: 'WEEKLY',
    order: 1,
  },
  {
    id: 'prog-2',
    title: 'Prayer for Pregnant Women & Families',
    dayOrFrequency: 'MONDAY',
    time: '9:00AM - 12:00PM',
    description: 'Prayer for pregnant women, the barren & the drivers wife.',
    category: 'WEEKLY',
    order: 2,
  },
  {
    id: 'prog-3',
    title: 'Bible Study',
    dayOrFrequency: 'TUESDAY',
    time: '5:00PM - 6:30PM',
    description: 'Diving deep into the scriptures and building spiritual foundations.',
    category: 'WEEKLY',
    order: 3,
  },
  {
    id: 'prog-4',
    title: 'Prayer for Motherhood',
    dayOrFrequency: 'WEDNESDAY',
    time: '9:00AM - 12:00PM',
    description: 'Intercession and fellowship for mothers and families.',
    category: 'WEEKLY',
    order: 4,
  },
  {
    id: 'prog-5',
    title: 'Meeting of the Prayer Warriors',
    dayOrFrequency: 'THURSDAY',
    time: '5:00PM - 7:00PM',
    description: 'Standing in the gap through fervent prayer and intercession.',
    category: 'WEEKLY',
    order: 5,
  },
  {
    id: 'prog-6',
    title: 'Sunday School Teachers Meeting',
    dayOrFrequency: 'FRIDAY',
    time: '5:00PM - 7:00PM',
    description: 'Preparation and study session for Sunday school teachers.',
    category: 'WEEKLY',
    order: 6,
  },
  {
    id: 'prog-7',
    title: 'Choir Practice & Ministers Meeting',
    dayOrFrequency: 'SATURDAY',
    time: 'Choir Practice (5:00pm-6:00pm) | Ministers Meeting (5:00pm-7:00pm)',
    description: 'Worship team rehearsal and church leadership meeting.',
    category: 'WEEKLY',
    order: 7,
  },
  {
    id: 'prog-8',
    title: 'Set Me Free',
    dayOrFrequency: 'FIRST SUNDAY OF THE MONTH',
    time: '10:00AM - 12:00PM',
    description: 'Special deliverance, breakthrough, and freedom service.',
    category: 'MONTHLY',
    order: 8,
  },
  {
    id: 'prog-9',
    title: 'Thanksgiving Service',
    dayOrFrequency: 'LAST SUNDAY OF THE MONTH',
    time: 'After Sermon',
    description: 'Praising and thanking God for His faithfulness throughout the month.',
    category: 'MONTHLY',
    order: 9,
  },
  {
    id: 'prog-10',
    title: 'Youth Night Vigil',
    dayOrFrequency: 'LAST FRIDAY OF THE MONTH',
    time: '12:00AM - 5:00AM',
    description: 'An all-night prayer, worship, and empowerment session for the youth.',
    category: 'MONTHLY',
    order: 10,
  },
  {
    id: 'prog-11',
    title: 'Choir Vigil',
    dayOrFrequency: 'EVERY LAST SUNDAY OF THE MONTH',
    time: '12:00AM - 5:00AM',
    description: 'All-night worship and praise vigil by the choir.',
    category: 'MONTHLY',
    order: 11,
  },
  {
    id: 'prog-12',
    title: "Worker's Seminar",
    dayOrFrequency: 'SECOND FRIDAY OF EVERY MONTH',
    time: 'Evening',
    description: 'Equipping and training church workers for excellence in ministry.',
    category: 'MONTHLY',
    order: 12,
  },
];

export const initialTeam: TeamMemberItem[] = [
  {
    id: 'team-1',
    name: "REV'D JAMES OYEGBILE",
    role: 'OUR GENERAL SUPERINTENDENT',
    quoteOrDescription: 'Leading with faith, wisdom, and a heart for souls.',
    imageUrl: '/image/1742890225837.jpg',
    order: 1,
  },
  {
    id: 'team-2',
    name: 'PASTOR MRS OLALEKAN OYEGBILE',
    role: 'OUR MID-WIFE',
    quoteOrDescription: 'Dedicated to helping women in giving birth to their foetus.',
    imageUrl: '/image/06.jpg',
    order: 2,
  },
  {
    id: 'team-3',
    name: 'Pastor Adetunji Adeyanju',
    role: 'ASSOCIATE PASTOR',
    quoteOrDescription: 'Dedicated to discipleship and community outreach.',
    imageUrl: '/image/10.jpg',
    order: 3,
  },
  {
    id: 'team-4',
    name: 'Pastor Tunde Adegboyega',
    role: 'CHOIR MASTER',
    quoteOrDescription: 'Bringing people into God’s presence through worship.',
    imageUrl: null,
    order: 4,
  },
  {
    id: 'team-5',
    name: 'Evangelist Adeoluwa Goodness',
    role: 'YOUTH AND CHILDREN LEADERS',
    quoteOrDescription: 'Nurturing the next generation in the love of Christ.',
    imageUrl: null,
    order: 5,
  },
  {
    id: 'team-6',
    name: 'Mr. Nathaniel Ojo',
    role: 'CHURCH ADMINISTRATOR',
    quoteOrDescription: 'Ensuring the smooth running of ministry operations.',
    imageUrl: null,
    order: 6,
  },
  {
    id: 'team-7',
    name: 'Pastor Nathaniel Ajibade',
    role: 'OUTREACH & EVANGELISM CO-ORDINATOR',
    quoteOrDescription: 'Reaching souls and sharing the Gospel worldwide.',
    imageUrl: null,
    order: 7,
  },
];
