import { ChurchInfo, SermonItem, ProgramEventItem, TeamMemberItem, TestimonialItem, GalleryImageItem } from './types';

export const churchInfo: ChurchInfo = {
  name: "ALL SOUL'S WINNING FOR SAVIOUR GLOBAL MINISTRY",
  shortName: 'ASWS Global Ministry',
  tagline:
    'Come experience the joy of belonging to a faith community that values community, worship, and purpose.',
  motto: 'Leading with faith, wisdom, and a heart for souls',
  address: 'Ayedire area behind royal college Ogbomosho, Oyo state, Nigeria',
  phone: '08035745728',
  email: 'oyegbilejames@gmail.com',
  pastor: "REV'D James Oyegbile",
  logoUrl: '/image/ALL_SOULS_WINNING_FOR_SAVIOUR_GLOBAL_MINISTRY-removebg-preview.png',
  copyrightYear: 2025,
  serviceTimes: {
    sundayService: 'Sunday Service: 9:30 AM - 12:00 PM',
    sundaySchool: 'Sunday School: 8:00 AM - 9:30 AM',
    workersPrayer: 'Workers Prayer: 7:00 AM - 8:00 AM',
    midweekPrayer: 'Wednesday Prayer: 9:00 AM - 12:00 PM',
    bibleStudy: 'Tuesday Bible Study: 5:00 PM - 6:30 PM',
  },
  socialLinks: {
    facebook: 'https://facebook.com/allsoulswinningforsaviour',
    youtube: 'https://youtube.com/@allsoulswinningforsaviour',
    instagram: 'https://instagram.com/allsoulswinningforsaviour',
    whatsapp: 'https://wa.me/2348035745728?text=Hello%20ASWS%20Global%20Ministry%2C%20I%20would%20like%20to%20connect%20for%20prayers%20and%20fellowship.',
    telegram: 'https://t.me/+2348035745728',
  },
  bankDetails: {
    bankName: 'GT BANK',
    accountName: 'Oyegbile James akinloye',
    accountNumber: '0049625425',
  },
};

export const initialSermons: SermonItem[] = [
  {
    id: 'sermon-1',
    title: 'The Power of Forgiveness',
    speaker: "REV'D James Oyegbile",
    date: '2024-10-27',
    description:
      'Discover the freedom that comes from forgiving others as Christ has forgiven us.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-2',
    title: 'Living a Life of Purpose',
    speaker: 'Pastor Adetunji Adeyanju',
    date: '2024-10-20',
    description: "Learn how to find and follow God's unique purpose for your life.",
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-3',
    title: 'Faith in Times of Trial',
    speaker: "REV'D James Oyegbile",
    date: '2024-10-13',
    description: 'A message of hope and perseverance through faith.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-4',
    title: 'The Joy of Giving',
    speaker: 'Pastor Tunde Adegboyega',
    date: '2024-10-06',
    description: 'Understanding the blessings that come with a generous heart.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-5',
    title: 'Walking in the Spirit',
    speaker: "REV'D James Oyegbile",
    date: '2024-09-29',
    description: 'How to live a life led by the Holy Spirit every day.',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'sermon-6',
    title: 'Love Your Neighbor',
    speaker: 'Pastor Adetunji Adeyanju',
    date: '2024-09-22',
    description: "Practical ways to show Christ's love to those around you.",
    videoUrl: '#',
    audioUrl: '#',
  },
];

export const initialEvents: ProgramEventItem[] = [
  {
    id: 'prog-1',
    title: 'Sunday Services',
    dayOrFrequency: 'SUNDAY',
    time: 'Workers Prayer (7:00am-8:00am) | Sunday School (8:00am-9:30am) | Sunday Service (9:30am-12:00pm)',
    description: 'Our main worship service, Sunday school, and workers preparation prayer.',
    category: 'WEEKLY',
    order: 1,
  },
  {
    id: 'prog-2',
    title: 'Prayer for Pregnant Women & Families',
    dayOrFrequency: 'MONDAY',
    time: '9:00AM - 12:00PM',
    description: 'Prayer for pregnant women, the barren & the drivers wife.',
    category: 'WEEKLY',
    order: 2,
  },
  {
    id: 'prog-3',
    title: 'Bible Study',
    dayOrFrequency: 'TUESDAY',
    time: '5:00PM - 6:30PM',
    description: 'Diving deep into the scriptures and building spiritual foundations.',
    category: 'WEEKLY',
    order: 3,
  },
  {
    id: 'prog-4',
    title: 'Prayer for Motherhood',
    dayOrFrequency: 'WEDNESDAY',
    time: '9:00AM - 12:00PM',
    description: 'Intercession and fellowship for mothers and families.',
    category: 'WEEKLY',
    order: 4,
  },
  {
    id: 'prog-5',
    title: 'Meeting of the Prayer Warriors',
    dayOrFrequency: 'THURSDAY',
    time: '5:00PM - 7:00PM',
    description: 'Standing in the gap through fervent prayer and intercession.',
    category: 'WEEKLY',
    order: 5,
  },
  {
    id: 'prog-6',
    title: 'Sunday School Teachers Meeting',
    dayOrFrequency: 'FRIDAY',
    time: '5:00PM - 7:00PM',
    description: 'Preparation and study session for Sunday school teachers.',
    category: 'WEEKLY',
    order: 6,
  },
  {
    id: 'prog-7',
    title: 'Choir Practice & Ministers Meeting',
    dayOrFrequency: 'SATURDAY',
    time: 'Choir Practice (5:00pm-6:00pm) | Ministers Meeting (5:00pm-7:00pm)',
    description: 'Worship team rehearsal and church leadership meeting.',
    category: 'WEEKLY',
    order: 7,
  },
  {
    id: 'prog-8',
    title: 'Set Me Free',
    dayOrFrequency: 'FIRST SUNDAY OF THE MONTH',
    time: '10:00AM - 12:00PM',
    description: 'Special deliverance, breakthrough, and freedom service.',
    category: 'MONTHLY',
    order: 8,
  },
  {
    id: 'prog-9',
    title: 'Thanksgiving Service',
    dayOrFrequency: 'LAST SUNDAY OF THE MONTH',
    time: 'After Sermon',
    description: 'Praising and thanking God for His faithfulness throughout the month.',
    category: 'MONTHLY',
    order: 9,
  },
  {
    id: 'prog-10',
    title: 'Youth Night Vigil',
    dayOrFrequency: 'LAST FRIDAY OF THE MONTH',
    time: '12:00AM - 5:00AM',
    description: 'An all-night prayer, worship, and empowerment session for the youth.',
    category: 'MONTHLY',
    order: 10,
  },
  {
    id: 'prog-11',
    title: 'Choir Vigil',
    dayOrFrequency: 'EVERY LAST SUNDAY OF THE MONTH',
    time: '12:00AM - 5:00AM',
    description: 'All-night worship and praise vigil by the choir.',
    category: 'MONTHLY',
    order: 11,
  },
  {
    id: 'prog-12',
    title: "Worker's Seminar",
    dayOrFrequency: 'SECOND FRIDAY OF EVERY MONTH',
    time: 'Evening',
    description: 'Equipping and training church workers for excellence in ministry.',
    category: 'MONTHLY',
    order: 12,
  },
];

export const initialTeam: TeamMemberItem[] = [
  {
    id: 'team-1',
    name: "REV'D JAMES OYEGBILE",
    role: 'OUR GENERAL SUPERINTENDENT',
    quoteOrDescription: 'Leading with faith, wisdom, and a heart for souls.',
    imageUrl: '/image/1742890223853-removebg-preview.png',
    order: 1,
  },
  {
    id: 'team-2',
    name: 'PASTOR MRS OLALEKAN OYEGBILE',
    role: 'OUR MID-WIFE',
    quoteOrDescription: 'Dedicated to helping women in giving birth to their foetus.',
    imageUrl: '/image/06.jpg',
    order: 2,
  },
  {
    id: 'team-3',
    name: 'Pastor Adetunji Adeyanju',
    role: 'ASSOCIATE PASTOR',
    quoteOrDescription: 'Dedicated to discipleship and community outreach.',
    imageUrl: '/image/10.jpg',
    order: 3,
  },
  {
    id: 'team-4',
    name: 'Pastor Tunde Adegboyega',
    role: 'CHOIR MASTER',
    quoteOrDescription: 'Bringing people into God’s presence through worship.',
    imageUrl: '/image/1742890221781.jpg',
    order: 4,
  },
  {
    id: 'team-5',
    name: 'Evangelist Adeoluwa Goodness',
    role: 'YOUTH AND CHILDREN LEADERS',
    quoteOrDescription: 'Nurturing the next generation in the love of Christ.',
    imageUrl: '/image/08.jpg',
    order: 5,
  },
  {
    id: 'team-6',
    name: 'Mr. Nathaniel Ojo',
    role: 'CHURCH ADMINISTRATOR',
    quoteOrDescription: 'Ensuring the smooth running of ministry operations.',
    imageUrl: '/image/1742890227792.jpg',
    order: 6,
  },
  {
    id: 'team-7',
    name: 'Pastor Nathaniel Ajibade',
    role: 'OUTREACH & EVANGELISM CO-ORDINATOR',
    quoteOrDescription: 'Reaching souls and sharing the Gospel worldwide.',
    imageUrl: '/image/1742890225837.jpg',
    order: 7,
  },
];

export const initialTestimonials: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Sister Deborah Akinwumi',
    locationOrRole: 'Ayedire Community, Ogbomosho',
    category: 'Family & Motherhood',
    title: 'Safe Delivery of Healthy Twins After 6 Years of Waiting',
    story:
      'For six long years after marriage, my husband and I faced continuous disappointment and medical despair. When we joined the Wednesday Prayer for Pregnant Women & Motherhood ministered by Pastor Mrs. Olalekan Oyegbile, she laid hands on me and prophesied: "Your tears of sorrow shall become tears of double joy." God remembered us! Within three months I conceived, and through every trimester the church stood in fervent prayer. I was delivered safely of healthy twin boys without any complications. God is faithful to His word!',
    scripture: '1 Samuel 1:27',
    date: '2024-11-12',
    isApproved: true,
  },
  {
    id: 'test-2',
    name: 'Brother Samuel Babatunde',
    locationOrRole: 'Youth Fellowship & Outreach Worker',
    category: 'Salvation & Purpose',
    title: 'Delivered from Addiction, Transformed into a Soul Winner',
    story:
      'Before coming to ASWS Global Ministry, my life was spiraling in secret addiction, depression, and hopelessness. I felt completely worthless. An evangelism team from the church met me on the streets of Ogbomosho and invited me with pure love. During the sermon by Rev\'d James Oyegbile on "Living a Life of Purpose", the Holy Spirit convicted my heart. At the altar call, chains broke off my soul. Today, by the power of Jesus Christ, I have been totally sober for over two years, baptized in the Holy Spirit, and actively leading fellow young people to Christ.',
    scripture: '2 Corinthians 5:17',
    date: '2024-10-18',
    isApproved: true,
  },
  {
    id: 'test-3',
    name: 'Elder Matthew Adeleke',
    locationOrRole: 'Men of Valor Fellowship',
    category: 'Healing & Deliverance',
    title: 'Miraculous Healing from Chronic Spinal Paralysis',
    story:
      'I suffered from severe lumbar spine degeneration that left me bedridden and unable to walk for almost five months. Doctors recommended a risky surgery with uncertain chances. During the monthly "Set Me Free" deliverance service, as Rev\'d Oyegbile called out cases under the anointing, heat flooded my spine. He told those believing God to stand up in faith. By the grace of Jesus, I rose up without any support! The chronic agonizing pain vanished instantly. Follow-up scans shocked the physicians. Jehovah Rapha healed me completely!',
    scripture: 'Jeremiah 30:17',
    date: '2024-09-04',
    isApproved: true,
  },
  {
    id: 'test-4',
    name: 'Sister Grace Folashade',
    locationOrRole: 'Choir Department Member',
    category: 'Family & Marriage',
    title: 'Divine Restoration of Our Broken Marriage',
    story:
      'My home was on the brink of divorce. Severe bitterness and unresolved conflicts had completely driven my husband away. I came weeping into the sanctuary during Tuesday Bible Study and subsequently received pastoral counseling with our General Superintendent. We learned the true biblical foundation of forgiveness and the J.O.Y. principle (Jesus First, Others Second, You Third). God softened my husband\'s heart and brought him back. Our marriage is sweeter and stronger today than on our wedding day!',
    scripture: 'Colossians 3:13-14',
    date: '2024-08-22',
    isApproved: true,
  },
  {
    id: 'test-5',
    name: 'Brother Emmanuel Oladipo',
    locationOrRole: 'Royal College Community Student',
    category: 'Deliverance & Freedom',
    title: 'Academic Breakthrough and Freedom from Night Torment',
    story:
      'I was tormented by recurring spiritual nightmares and overwhelming anxiety that caused me to fail crucial university exams repeatedly. I could not sleep without terror. When I attended the Prayer Warriors meeting on Thursday, the brethren interceded with authority in the name of Jesus. The oppressive darkness lifted like a cloud. That semester, God blessed me with distinction grades and unexplainable peace of mind. God is truly alive in this ministry!',
    scripture: '2 Timothy 1:7',
    date: '2024-07-30',
    isApproved: true,
  },
  {
    id: 'test-6',
    name: 'Sister Victoria Alabi',
    locationOrRole: 'Market Women Fellowship',
    category: 'Provision & Thanksgiving',
    title: 'Unexpected Business Favor & Debt Cancellation',
    story:
      'I was buried under crippling debt and faced the confiscation of my trading goods. During a Sunday celebration service on "The Joy of Giving", I sowed my humble seed in faith and partnered with the church outreach fund. Within two weeks, a long-forgotten client settled a massive overdue contract, and new wholesale doors opened beyond my imagination. My debts were completely paid off! To God alone be all the glory!',
    scripture: 'Philippians 4:19',
    date: '2024-06-15',
    isApproved: true,
  },
];

export const initialGalleryImages: GalleryImageItem[] = [
  {
    id: 'gal-1',
    title: "Rev'd James Oyegbile Ministering the Word of Grace",
    category: 'WORSHIP',
    description: 'Our General Superintendent proclaiming the transformative message of salvation, spiritual breakthrough, and holy living.',
    imageUrl: '/image/1742890225837.jpg',
    date: '2024-11-24',
    location: 'Main Sanctuary, Ayedire, Ogbomosho',
    featured: true,
  },
  {
    id: 'gal-2',
    title: 'Community Outreach & Evangelism in Ayedire',
    category: 'OUTREACH',
    description: 'Evangelism workers and church members reaching out with the Gospel, praying with families and distributing Christian literature in Ogbomosho.',
    imageUrl: '/image/1742890227792.jpg',
    date: '2024-11-09',
    location: 'Ayedire Community & Royal College Area',
    featured: true,
  },
  {
    id: 'gal-3',
    title: 'Annual Deliverance & Victory Convention',
    category: 'EVENTS',
    description: 'The congregation united in fervent praise, worship, and thanksgiving during the annual victory convention celebration.',
    imageUrl: '/image/08.jpg',
    date: '2024-10-27',
    location: 'ASWS Global Ministry Cathedral',
    featured: true,
  },
  {
    id: 'gal-4',
    title: 'Motherhood Prayer & Blessing Session',
    category: 'PROGRAMS',
    description: 'Pastor Mrs. Olalekan Oyegbile leading the weekly prayer service for expectant mothers, pregnant women, and families believing God for children.',
    imageUrl: '/image/06.jpg',
    date: '2024-11-13',
    location: 'Mothers & Family Fellowship Hall',
    featured: true,
  },
  {
    id: 'gal-5',
    title: 'Youth Fellowship & Soul Winners Rally',
    category: 'OUTREACH',
    description: 'Passionate youth ministers and evangelists gathering to pray and mobilize for campus and marketplace outreach missions.',
    imageUrl: '/image/1742890223853.jpg',
    date: '2024-10-19',
    location: 'Ogbomosho Central Streets',
    featured: false,
  },
  {
    id: 'gal-6',
    title: 'Choir Ministration & High Praise',
    category: 'WORSHIP',
    description: 'The ASWS sanctuary choir and musicians lifting up spiritual songs and ushering worshippers into the glory of God.',
    imageUrl: '/image/1742890221781.jpg',
    date: '2024-11-17',
    location: 'Worship Chancel, Main Sanctuary',
    featured: true,
  },
  {
    id: 'gal-7',
    title: 'Discipleship Teaching with Pastor Adeyanju',
    category: 'PROGRAMS',
    description: 'Interactive Tuesday Bible Study and discipleship foundations training empowering believers in the scriptures.',
    imageUrl: '/image/10.jpg',
    date: '2024-11-05',
    location: 'Main Sanctuary',
    featured: false,
  },
  {
    id: 'gal-8',
    title: 'All-Night Deliverance Vigil "Set Me Free"',
    category: 'EVENTS',
    description: 'Midnight deliverance and prophetic prayer vigils breaking chains, granting physical healing, and spiritual breakthroughs.',
    imageUrl: '/image/church_prayer_vigil.jpg',
    date: '2024-10-25',
    location: 'Sanctuary & Overflow Grounds',
    featured: true,
  },
  {
    id: 'gal-9',
    title: 'Community Relief & Love Welfare Outreach',
    category: 'OUTREACH',
    description: 'Demonstrating the love of Christ by distributing food packages, welfare packages, and school supplies to local community residents.',
    imageUrl: '/image/03.jpg',
    date: '2024-09-28',
    location: 'Ayedire Outreach Center',
    featured: false,
  },
  {
    id: 'gal-10',
    title: 'Sunday School & Children Church Assembly',
    category: 'PROGRAMS',
    description: 'Equipping our children and adolescents with biblical values, hymns, memory verses, and Christ-centered character.',
    imageUrl: '/image/sunday_school_children.jpg',
    date: '2024-11-10',
    location: 'Children & Youth Chapel',
    featured: false,
  },
  {
    id: 'gal-11',
    title: 'Missionaries Commissioning & Intercession',
    category: 'OUTREACH',
    description: 'Pastoral team laying on of hands and interceding for missionary leaders sent into rural communities and neighboring regions.',
    imageUrl: '/image/church_welcome_entrance.jpg',
    date: '2024-08-14',
    location: 'Main Altar',
    featured: false,
  },
  {
    id: 'gal-12',
    title: 'Thanksgiving & Family Dedication Celebration',
    category: 'EVENTS',
    description: 'Joyful praise, dancing, and heartfelt dedication of new children and testimonies of God’s faithfulness throughout the year.',
    imageUrl: '/image/thanksgiving_celebration.jpg',
    date: '2024-11-24',
    location: 'Main Sanctuary',
    featured: false,
  },
];


